apiVersion: v1
kind: ConfigMap
metadata:
  name: config-test
data:
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=100
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true