# SA
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-user
  namespace: default

---
# Role

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-exec-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]

---
# RoleBinding

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-exec-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-exec-role
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: app-user
    namespace: default

